apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4hqy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0017-tenant/ci1t-43256-0017-app/devfile-sample-4hqy@sha256:43ca644c8025f2898500a12683ed31545b89c007c19c1e46817699b327d84b1f
        name: my-nodejs
        resources: {}
status: {}
